[package]
name = "lambdacalc"
version = "1.4.0"
edition = "2018"
authors = ["Evert Provoost <evert.provoost@gmail.com>"]

[dependencies]
crossbeam-channel = "0.4.2"
ctrlc = "3.1.4"
rustyline = "6.1.2"

[[bin]]
name = "cLC"
